### ISSUE TITLE
Global WordPress functions are reported missing

### ISSUE THREAD

**Issue by TitanNano** [php-integrator/atom-linter#53]
I recently set up a WordPress project but for some reason php-integrator can't find many of the global functions.
Please tell me what I can provide to debug this.

**Comment by Gert-dev** [comment]
Are these global functions namespaced by any chance?

**Comment by TitanNano** [comment]
I don't thinks so. This is one of the functions.

https://github.com/WordPress/WordPress/blob/4.6-branch/wp-includes/plugin.php#L321

**Comment by Gert-dev** [comment]
Hmm.. indexing the file in PHP 7 seems to work, so it's not a parsing failure due to some corner case. What version of PHP are you using and what happens if you modify that file in your codebase, then undo the change and then modify the file that is showing the linter errors about the functions not being found? Do they suddenly disappear or do they remain visible?

**Comment by TitanNano** [comment]
It seems the issue got fixed by one of the recent updates.
