### ISSUE TITLE
Reports global constants as "not found" if array

### ISSUE THREAD

**Issue by fridde** [php-integrator/atom-linter#56]
This is a weird behaviour I can't wrap my head around:

If I use a user-defined constant defined in a different file (but within the same project), the linter *only* gives an error of the kind ` "The global constant <strong>#{item.name}</strong> was not found."` if the corresponding constant's value is an array (which is allowed since PHP 7.0.0), but *not* if the value is a string or other primitive value.

If the constant is defined within the same file, no error is reported.

Changing `showUnknownGlobalConstants` to `false` and restarting Atom removes any errors of this kind, as expected.

Any idea as to where this could come from?

**Comment by Gert-dev** [comment]
Sounds like a bug. It is possible the core doesn't know how to properly handle the array default value and then proceeds without indexing it, hence not being able to find it later on.

I've copied this issue to the core (since GitHub doesn't allow moving issues) as it's most likely an issue there. Feel free to watch [the new one](https://github.com/php-integrator/core/issues/90) to continue receiving GitHub notifications.
