### ISSUE TITLE
Incorrect param type

### ISSUE THREAD

**Issue by sharifzadesina** [php-integrator/atom-linter#60]
As you can see the below image param type is correct but linter detects it as an incorrect param type.

![screenshot from 2017-05-26 20-09-10](https://cloud.githubusercontent.com/assets/15300551/26501502/17203960-424f-11e7-9310-0e1192397fee.png)

**Comment by Gert-dev** [comment]
This is a bug in the stable version's type checking code. I've already fixed this issue in the development branch and a fix for it will be included in the 3.0 release.

I'll close this since it's a bug in the core. The core ticket can be found [here](https://gitlab.com/php-integrator/core/issues/89).
